# Copyright (c) 2026 Timo Duttine
# SPDX-License-Identifier: BUSL-1.1

@version: 4.10
@include "scl.conf"

options {
  chain_hostnames(no);
  keep_hostname(yes);
  use_dns(no);
  create_dirs(yes);
  flush_lines(1);
  log_fifo_size(20000);
  stats(freq(0));
};

source s_net {
  udp(ip("0.0.0.0") port(514));
};

destination d_file {
  file("/var/log/syslog-ng/${HOST}_${YEAR}-${MONTH}-${DAY}.log");
};

log {
  source(s_net);
  destination(d_file);
};
